version: '3.7'

services:

    ethereum_api:
        image: ${something_IMAGE_NAME:-something}
        build:
            context: .
            dockerfile: Dockerfile
            target: development
            args:
                something: something
        depends_on:
            - mongo
        stdin_open: true
        tty: true
        container_name: something
        volumes:
            - ./:/app
            - ethereum_api_node_modules:/app/node_modules
        ports:
            - 8080:8080
            - 9229:9229

    mongo:
        image: mongo:4.0.11-xenial
        container_name: mongo
        command: --smallfiles
        environment:
            - MONGO_INITDB_ROOT_USERNAME=mongoadmin
            - MONGO_INITDB_ROOT_PASSWORD=secret
        ports:
            - 27017:27017

    mongo_express:
        image: mongo-express
        container_name: mongo_express
        logging:
            driver: none
        depends_on:
            - mongo
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=mongoadmin
            - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
        ports:
            - 8081:8081


    ####################
    ### MR. MEESEEKS ###
    ####################

    # Look at me! I'm Mr. Meeseeks who feeds the database
    meeseek_mongo_feed:
        image: mongo:4.0.11-xenial
        container_name: meeseek_mongo_feed
        depends_on:
            - mongo
        environment:
            - ME_CONFIG_MONGODB_ADMINUSERNAME=mongoadmin
            - ME_CONFIG_MONGODB_ADMINPASSWORD=secret
        volumes:
            - ./data:/backup
        command: sh /backup/something

volumes:
    something_node_modules:
networks:
    default:
        name: something-environment-network
